# Generated by Django 4.2.7 on 2023-11-19 23:34

import alumnos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('curso', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('año', models.CharField(choices=[('1°', 'Primero'), ('2°', 'Segundo'), ('3°', 'Tercero'), ('4°', 'Cuarto'), ('5°', 'Quinto')], max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=alumnos.models.user_pic_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_examen', to='alumnos.alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_examen', to='examenes.examen')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='examen',
            field=models.ManyToManyField(related_name='alumno', through='alumnos.AlumnoExamen', to='examenes.examen'),
        ),
    ]
