# Generated by Django 4.2.3 on 2023-09-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumnoexamen_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='año',
            field=models.CharField(choices=[('1°', 'Primero'), ('2°', 'Segundo'), ('3°', 'Tercero'), ('4°', 'Cuarto'), ('5°', 'Quinto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=50),
        ),
    ]
