# Generated by Django 4.2.7 on 2023-11-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoexamen',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
