# Generated by Django 4.2.7 on 2023-11-19 23:34

from django.db import migrations, models
import django.db.models.deletion
import examenes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('curso', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('año', models.CharField(choices=[('1°', '1°'), ('2°', '2°'), ('3°', '3°'), ('4°', '4°'), ('5°', '5°')], max_length=50)),
                ('materia', models.CharField(choices=[('historia', 'Historia'), ('etica', 'Etica')], max_length=70)),
                ('image', models.ImageField(blank=True, null=True, upload_to=examenes.models.examen_img_path)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('puntaje', models.DecimalField(decimal_places=1, max_digits=2)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='examenes.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='examenes.pregunta')),
            ],
        ),
    ]
