# Generated by Django 4.2.7 on 2023-11-29 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_remove_examen_time_examen_end_examen_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
