# Generated by Django 4.2.3 on 2023-08-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_alter_respuesta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='examenes.examen'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='examenes.pregunta'),
        ),
    ]
