# Generated by Django 4.2.3 on 2023-09-20 17:01

from django.db import migrations, models
import examenes.models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_alter_pregunta_examen_alter_respuesta_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=examenes.models.examen_img_path),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='puntaje',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
