# Generated by Django 4.2.3 on 2023-09-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0006_alter_examen_año_alter_examen_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='materia',
            field=models.CharField(choices=[('historia', 'Historia'), ('etica', 'Etica')], max_length=70),
        ),
    ]
