# Generated by Django 4.2.3 on 2023-09-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0007_alter_examen_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='curso',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50),
        ),
    ]
